apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: r53-credentials
  namespace: cert-manager
spec:
  refreshInterval: {{ .Values.refreshInterval }}
  secretStoreRef:
    kind: {{ .Values.securityStore.kind }}
    name: {{ .Values.securityStore.name }}
  target:
    name: r53-secret-key
    creationPolicy: Owner
  data:
    - secretKey: secret-access-key
      remoteRef:
        key: {{.Values.credentials.keyPath}}
        property: value
    - secretKey: access-key-id
      remoteRef:
        key: {{.Values.credentials.keyPath}}
        property: access-key-id
