apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespace | default "cert-manager" }}
  labels:
    {{- if eq .Values.ingressMode "ambient" }}
    istio.io/dataplane-mode: ambient
    {{- end }}
