---

apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: {{ .Values.poolName | default "local-pool"}}-l2
  namespace: metallb-system
spec:
  ipAddressPools:
    - {{ .Values.poolName | default "local-pool"}}
