apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ngrok-argocd-webhook
  namespace: argocd
spec:
  ingressClassName: ngrok
  rules:
    - host: {{ .Values.argoNgrokEndpoint }}
      http:
        paths:
          - path: /api/webhook
            pathType: Prefix
            backend:
              service:
                name: argocd-server
                port:
                  number: 80