---

apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ngrok-operator-credentials
  namespace: {{ .Values.namespace | default "ngrok-ingress" }}
spec:
  refreshInterval: {{ .Values.secretRefreshInterval }}
  secretStoreRef:
    name: {{ .Values.clusterIssuer.name }}
    kind: {{ .Values.clusterIssuer.kind }}
  target:
    name: ngrok-operator-credentials
    creationPolicy: Owner
  data:
    - secretKey: AUTHTOKEN
      remoteRef:
        key: shared/argocd/main/proxy
        property: auth-token
    - secretKey: API_KEY
      remoteRef:
        key: shared/argocd/main/proxy
        property: api-key
