apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespace | default "ngrok-ingress"}}
  labels:
    {{- if eq .Values.ingressMode "ambient" }}
    istio.io/dataplane-mode: ambient
    {{- end }}