apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: argocd-admin-password
  namespace: argocd
spec:
  refreshInterval: {{ .Values.secretRefreshInterval }}
  secretStoreRef:
    kind: {{ .Values.securityStore.kind }}
    name: {{ .Values.securityStore.name }}
  target:
    name: argocd-secret
    creationPolicy: Owner
  data:
    - secretKey: admin.password
      remoteRef:
        key: shared/argocd
        property: admin-password
    - secretKey: admin.passwordMtime
      remoteRef:
        key: shared/argocd
        property: admin-password-mtime