apiVersion: v1
kind: Service
metadata:
  name: argocd-server-cli
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-server-cli
    app.kubernetes.io/part-of: argocd
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app.kubernetes.io/name: argocd-server
