apiVersion: gateway.networking.k8s.io/v1beta1
kind: Gateway
metadata:
  name: argocd-gateway
  namespace: {{ .Values.namespace | default "argocd" }}
spec:
  gatewayClassName: istio
  listeners:
    - name: https
      port: 443
      protocol: HTTPS
      hostname: {{ .Values.hostName }}
      tls:
        mode: Terminate
        certificateRefs:
          - name: argocd-server-tls
            kind: Secret
