apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: argocd-github-webhook
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: argocd
spec:
  refreshInterval: "1m"
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: argocd-github-webhook
    creationPolicy: Owner
  data:
    - secretKey: token
      remoteRef:
        key: shared/argocd/main/proxy
        property: repo-token
