apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: github-token
  namespace: {{ .Values.namespace | default "argocd" }}
spec:
  refreshInterval: {{ .Values.secretRefreshInterval }}
  secretStoreRef:
    kind: {{ .Values.securityStore.kind }}
    name: {{ .Values.securityStore.name }}
  target:
    name: github-token
    creationPolicy: Owner
  data:
    - secretKey: password
      remoteRef:
        key: shared/gh_argo_secret
        property: password
