---

apiVersion: v1
kind: ConfigMap
metadata:
  name: 'kustomized-helm'
  namespace: argocd
data:
  kustomized-helm.yaml: |
    apiVersion: argoproj.io/v1alpha1
    kind: ConfigManagementPlugin
    metadata:
      name: 'kustomized-helm'
    spec:
      init:
        command: ["/bin/sh", "-c"]
        args: [
          'export HOME=/tmp && helm repo add hyper-helm https://hypermedia-tech.github.io/hyper-helm-charts && helm repo update'
        ]
      generate:
        command: ["/bin/sh", "-c"]
        args: [
          'export HOME=/tmp && kustomize build --enable-helm > ../../../../base/all.yaml && kustomize build ../../../../base'
        ]
