---

apiVersion: v1
kind: ConfigMap
metadata:
  name: 'kustomized-helm'
  namespace: '{{ .Values.namespace | default "argocd" }}'
data:
  kustomized-helm.yaml: |
    apiVersion: argoproj.io/v1alpha1
    kind: ConfigManagementPlugin
    metadata:
      name: 'kustomized-helm'
      namespace: '{{ .Values.namespace | default "argocd" }}'
    spec:
      init:
        command: ["/bin/sh", "-c"]
        args: [
          'export HOME=/tmp && helm repo add hyper-helm {{ .Values.helmRepository }} && helm repo update'
        ]
      generate:
        command: ["/bin/sh", "-c"]
        args: [
          'export HOME=/tmp && kustomize build --enable-helm > ../../../../base/all.yaml && kustomize build ../../../../base'
        ]
