apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: argocd-github-webhook
  namespace: {{ .Values.namespace | default "argocd" }}
  labels:
    app.kubernetes.io/part-of: argocd
spec:
  refreshInterval: {{ .Values.secretRefreshInterval }}
  secretStoreRef:
    kind: {{ .Values.securityStore.kind }}
    name: {{ .Values.securityStore.name }}
  target:
    name: argocd-github-webhook
    creationPolicy: Owner
  data:
    - secretKey: token
      remoteRef:
        key: shared/argocd/main/proxy
        property: repo-token
