apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: target-cluster-secret
  namespace: argocd
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: {{ .Values.securityStore.name }}
    kind: {{ .Values.securityStore.kind }}
  target:
    name: target-cluster-secret
    creationPolicy: Owner
    template:
      metadata:
        labels:
          argocd.argoproj.io/secret-type: cluster
          environment: "gitops"
      data:
        name: target-cluster
        server: "{{ `{{ .server }}` }}"
        config: |
          {
            "tlsClientConfig": {
              "certData": "{{ `{{ .client_certificate_data }}` }}",
              "keyData": "{{ `{{ .client_key_data }}` }}",
              "caData": "{{ `{{ .certificate_authority_data }}` }}",
              "insecure": false
            }
          }
  data:
    - secretKey: client_certificate_data
      remoteRef:
        key: shared/argocd/clients/target-cluster
        property: client-cert-data
    - secretKey: client_key_data
      remoteRef:
        key: shared/argocd/clients/target-cluster
        property: client-key-data
    - secretKey: certificate_authority_data
      remoteRef:
        key: shared/argocd/clients/target-cluster
        property: ca-data
    - secretKey: server
      remoteRef:
        key: shared/argocd/clients/target-cluster
        property: target-cluster-url