{{- if .Values.repoAccess }}
{{- range .Values.repoAccess }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .name }}-secret
  namespace: {{ $.Values.namespace | default "argocd" }}
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: {{ $.Values.securityStore.name }}
    kind: {{ $.Values.securityStore.kind }}
  target:
    name: {{ .name }}-secret
    creationPolicy: Owner
    template:
      metadata:
        labels:
          argocd.argoproj.io/secret-type: cluster
          environment: "gitops"
      data:
        name: {{ .name }}
        server: "{{ `{{ .server }}` }}"
        config: |
          {
            "tlsClientConfig": {
              "certData": "{{ `{{ .client_certificate_data }}` }}",
              "keyData": "{{ `{{ .client_key_data }}` }}",
              "caData": "{{ `{{ .certificate_authority_data }}` }}",
              "insecure": false
            }
          }
  data:
    - secretKey: client_certificate_data
      remoteRef:
        key: {{ .secretPath }}
        property: client-cert-data
    - secretKey: client_key_data
      remoteRef:
        key: {{ .secretPath }}
        property: client-key-data
    - secretKey: certificate_authority_data
      remoteRef:
        key: {{ .secretPath }}
        property: ca-data
    - secretKey: server
      remoteRef:
        key: {{ .secretPath }}
        property: target-cluster-url
{{- end }}
{{- end }}