apiVersion: gateway.networking.k8s.io/v1beta1
kind: Gateway
metadata:
  name: jaeger-gateway
  namespace: istio-system
spec:
  gatewayClassName: istio
  listeners:
    - name: https
      port: 443
      protocol: HTTPS
      hostname: jaeger.hypermedia.au
      tls:
        mode: Terminate
        certificateRefs:
          - name: jaeger-tls-cert
            kind: Secret
            namespace: istio-system
