{{- if .Values.hostName }}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: jaeger-http-route
  namespace: {{ .Values.namespace }}
spec:
  hostnames:
    - {{ .Values.hostName }}
  parentRefs:
    - name: jaeger-gateway
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: jaeger-query
          port: 16686
  {{- end }}