hostName: ""
ingressMode: ambient
namespace: &ns minio
clusterIssuer:
  name: letsencrypt-prod
  kind: ClusterIssuer
tenant:
  tenant:
    name: hyper-store
    image:
      repository: quay.io/minio/minio
      tag: RELEASE.2024-11-07T00-52-20Z
    pools:
      - servers: 2
        name: pool-0
        volumesPerServer: 2
        size: 20Gi
        storageClassName: nfs-client
        securityContext:
          runAsUser: 1001
          runAsGroup: 1001
          fsGroup: 1001
    certificate:
      requestAutoCert: false
    exposeServices:
      console: false
      minio: false
    metrics:
      enabled: true
      port: 9000
      protocol: http
    buckets:
      - name: loki-admin
        objectLock: false
      - name: loki-chunks
        objectLock: false
      - name: loki-ruler
        objectLock: false
