{{- if .Values.domainName }}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: grafana-http-route
  namespace: {{ .Values.namespace | default "monitoring"}}
spec:
  hostnames:
    - grafana.{{ .Values.domainName }}
  parentRefs:
    - name: grafana-gateway
      namespace: monitoring
      kind: Gateway
      group: gateway.networking.k8s.io
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: prometheus-stack-grafana
          port: 80
          group: ''
          kind: Service
          weight: 1
{{- end }}