{{- if .Values.domainName }}
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: grafana-gateway
  namespace: {{ .Values.namespace | default "monitoring"}}
spec:
  gatewayClassName: istio
  listeners:
    - name: https
      port: 443
      protocol: HTTPS
      hostname: grafana.{{ .Values.domainName }}
      tls:
        mode: Terminate
        certificateRefs:
          - name: grafana-tls-cert
            kind: Secret
            namespace: {{ .Values.namespace | default "monitoring"}}
            group: ''
  {{- end }}