{{- if .Values.domainName }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: grafana-tls-cert
  namespace: {{ .Values.namespace | default "monitoring"}}
spec:
  secretName: grafana-tls-cert
  commonName: grafana.{{ .Values.domainName }}
  dnsNames:
    - grafana.{{ .Values.domainName }}
  issuerRef:
    name: {{ .Values.clusterIssuer.name }}
    kind: {{ .Values.clusterIssuer.kind }}
  {{- end }}