apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: prometheus-tls-cert
  namespace: {{ .Values.namespace | default "monitoring"}}
spec:
  secretName: prometheus-tls-cert
  commonName: prometheus.{{ .Values.domainName }}
  dnsNames:
    - prometheus.{{ .Values.domainName }}
  issuerRef:
    name: {{ .Values.clusterIssuer.name }}
    kind: {{ .Values.clusterIssuer.kind }}
