{{- if .Values.domainName }}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: prometheus-http-route
  namespace: {{ .Values.namespace | default "monitoring"}}
spec:
  hostnames:
    - prometheus.{{ .Values.domainName }}
  parentRefs:
    - name: prometheus-gateway
      namespace: monitoring
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: prometheus-stack-kube-prom-prometheus
          port: 9090
{{- end }}