apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: loki-s3-creds
  namespace: {{ .Values.namespace | default "loki" }}
spec:
  refreshInterval: {{ .Values.secretRefreshInterval | default "1m" }}
  secretStoreRef:
    name: {{ .Values.secretStore.name }}
    kind: {{ .Values.secretStore.kind }}
  target:
    name: loki-s3-creds
    creationPolicy: Owner
  data:
    - secretKey: S3ACCESSKEYID
      remoteRef:
        key: shared/loki
        property: bucket-access-key-id
    - secretKey: S3SECRETACCESSKEY
      remoteRef:
        key: shared/loki
        property: bucket-access-key-secret
