apiVersion: v2
name: hyper-promtail
description: A chart wrapping promtail with overridable env affordances
type: application
version: 0.0.1

appVersion: "1.0"

dependencies:
  - name: promtail
    version: 6.16.6
    repository: https://grafana.github.io/helm-charts