apiVersion: v2
name: hyper-grafana-operator
description: A chart wrapping grafana operator with overridable env affordances
type: application
version: 0.0.3

appVersion: "1.0"

dependencies:
  - name: grafana-operator
    version: 4.9.10
    repository: https://charts.bitnami.com/bitnami