{{- if .Values.hostName }}
apiVersion: gateway.networking.k8s.io/v1beta1
kind: Gateway
metadata:
  name: kiali-gateway
  namespace: {{ .Values.namespace | default "kiali-system" }}
spec:
  gatewayClassName: istio
  listeners:
    - name: https
      port: 443
      protocol: HTTPS
      hostname: {{ .Values.hostName }}
      tls:
        mode: Terminate
        certificateRefs:
          - name: kiali-tls-cert
            kind: Secret
            namespace: {{ .Values.namespace | default "kiali-system" }}
{{- end }}