{{- if .Values.hostName }}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: kiali-http-route
  namespace: istio-system
spec:
  hostnames:
    - {{ .Values.hostName }}
  parentRefs:
    - name: kiali-gateway
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: kiali
          port: 20001
  {{- end }}