{{- if .Values.hostName }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: kiali-tls-cert
  namespace: istio-system
spec:
  secretName: kiali-tls-cert
  commonName: {{ .Values.hostName }}
  dnsNames:
    - {{ .Values.hostName }}
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
{{- end }}