{{- if .Values.uIhostName }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: pgadmin-tls-cert
  namespace: {{ .Values.namespace | default "postgres" }}
spec:
  secretName: pgadmin-tls-cert
  commonName: {{ .Values.uIhostName }}
  dnsNames:
    - {{ .Values.uIhostName }}
  issuerRef:
    name: {{ .Values.clusterIssuer.name }}
    kind: {{ .Values.clusterIssuer.kind }}
{{- end }}