apiVersion: gateway.networking.k8s.io/v1beta1
kind: Gateway
metadata:
  name: pgadmin-gateway
  namespace: postgres
spec:
  gatewayClassName: istio
  listeners:
    - name: https
      port: 443
      protocol: HTTPS
      hostname: pgadmin.hypermedia.au
      tls:
        mode: Terminate
        certificateRefs:
          - name: pgadmin-tls-cert
            kind: Secret
            namespace: postgres

