apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: pgadmin-http-route
  namespace: {{ .Values.namespace | default "postgres" }}
spec:
  hostnames:
    - {{ .Values.uIhostName }}
  parentRefs:
    - name: pgadmin-gateway
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: pgadmin4
          port: 80
