apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: pgadmin-http-route
  namespace: postgres
spec:
  hostnames:
    - "pgadmin.hypermedia.au"
  parentRefs:
    - name: pgadmin-gateway
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: pgadmin4
          port: 80
