{{- if .Values.hostName }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Values.name }}-tls-cert
  namespace: {{ .Values.namespace | default "argo" }}
spec:
  secretName: {{ .Values.name }}-tls-cert
  commonName: {{ .Values.hostName }}
  dnsNames:
    - {{ .Values.hostName }}
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
{{- end }}
