{{- if .Values.hostName }}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: argo-workflows-http-route
  namespace: {{ .Values.namespace | default "argo" }}
spec:
  hostnames:
    - {{ .Values.hostName }}
  parentRefs:
    - name: argo-workflows-gateway
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: hyper-argo-workflows-server
          port: 2746
{{- end -}}