apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: pihole-tls-cert
  namespace: {{ .Values.namespace | default "pihole-system" }}
spec:
  secretName: pihole-tls-cert
  commonName: {{ .Values.hostName }}
  dnsNames:
    - {{ .Values.hostName }}
  issuerRef:
    name: {{ .Values.clusterIssuer.name }}
    kind: {{ .Values.clusterIssuer.kind }}
