{{- if .Values.hostName }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: minio-tls-cert
  namespace: {{ .Values.namespace | default "minio" }}
spec:
  secretName: minio-tls-cert
  commonName: {{ .Values.hostName }}
  dnsNames:
    - {{ .Values.hostName }}
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  {{- end }}