{{- if .Values.hostName }}
apiVersion: gateway.networking.k8s.io/v1beta1
kind: Gateway
metadata:
  name: minio-gateway
  namespace: {{ .Values.namespace | default "minio" }}
spec:
  gatewayClassName: istio
  listeners:
    - name: https
      port: 443
      protocol: HTTPS
      hostname: {{ .Values.hostname }}
      tls:
        mode: Terminate
        certificateRefs:
          - name: minio-tls-cert
            kind: Secret
            namespace: minio

---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: Gateway
metadata:
  name: console-minio-gateway
  namespace: minio
spec:
  gatewayClassName: istio
  listeners:
    - name: https
      port: 443
      protocol: HTTPS
      hostname: console.{{ .Values.hostname }}
      tls:
        mode: Terminate
        certificateRefs:
          - name: console-minio-tls-cert
            kind: Secret
            namespace: minio
{{- end -}}