{{- if .Values.hostName }}
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: minio-http-route
  namespace: {{ .Values.namespace | default "minio" }}
spec:
  hostnames:
    - s3.{{ .Values.hostName }}
  parentRefs:
    - name: minio-gateway
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: hyper-store-hl
          port: 9000

---

apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: console-minio-http-route
  namespace: {{ .Values.namespace | default "minio" }}
spec:
  hostnames:
    - console.{{ .Values.hostName }}
  parentRefs:
    - name: console-minio-gateway
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: hyper-store-console
          port: 9090
{{- end -}}