{{- if .Values.hostName }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: console-minio-tls-cert
  namespace: {{ .Values.namespace | default "minio" }}
spec:
  secretName: console-minio-tls-cert
  commonName: console.{{ .Values.hostName }}
  dnsNames:
    - console.{{ .Values.hostName }}
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  {{- end }}