{{- if .Values.hostName }}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: dynamodb-http-route
  namespace: {{ .Values.namespace | default "dynamodb" }}
spec:
  hostnames:
    - {{ .Values.hostName }}
  parentRefs:
    - name: dynamodb-gateway
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: dynamodb
          port: 8001
{{- end }}