---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.serviceName }}-headless
  namespace: {{ .Values.namespace }}
spec:
  clusterIP: None
  selector:
    app: {{ .Values.serviceName }}
  ports:
    {{- range .Values.container.containerPorts }}
    - name: {{ .portName }}
      port: {{ .servicePort }}
      targetPort: {{ .portNumber }}
      protocol: {{ .protocol }}
    {{- end }}