apiVersion: gateway.networking.k8s.io/v1beta1
kind: Gateway
metadata:
  name: komoplane-gateway
  namespace: {{ .Values.namespace | default "crossplane-system" }}
spec:
  gatewayClassName: istio
  listeners:
    - name: https
      port: 443
      protocol: HTTPS
      hostname: komo.hypermedia.au
      tls:
        mode: Terminate
        certificateRefs:
          - name: komoplane-tls-cert
            kind: Secret
            namespace: {{ .Values.namespace | default "crossplane-system" }}

