{{- if .Values.uiHostName }}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: komoplane-http-route
  namespace: {{ .Values.namespace | default "crossplane-system" }}
spec:
  hostnames:
    - "komo.hypermedia.au"
  parentRefs:
    - name: komoplane-gateway
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: {{ .Values.env }}-{{ .Values.stripe }}-crossplane-komoplane
          port: 8090
  {{- end }}