{{- if .Values.uiHostName }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: komoplane-tls-cert
  namespace: {{ .Values.namespace | default "crossplane-system" }}
spec:
  secretName: komoplane-tls-cert
  commonName: {{ .Values.uiHostName }}
  dnsNames:
    - {{ .Values.uiHostName }}
  issuerRef:
    name: {{ .Values.securityStore.name }}
    kind: {{ .Values.securityStore.kind }}
  {{- end }}