namespace: monitoring
ingressMode: ambient
clusterIssuer:
  name: letsencrypt-prod
  kind: ClusterIssuer
kube-prometheus-stack:
  crds:
    enabled: true
  alertmanager:
    alertmanagerSpec:
      storage:
        volumeClaimTemplate:
          spec:
            storageClassName: "nfs-client"
            accessModes: [ "ReadWriteOnce" ]
            resources:
              requests:
                storage: 100Mi
  prometheus:
    prometheusSpec:
      storageSpec:
        volumeClaimTemplate:
          spec:
            storageClassName: "nfs-client"
            accessModes: [ "ReadWriteOnce" ]
            resources:
              requests:
                storage: 1Gi

  grafana:
    additionalDataSources:
      - name: loki-logs
        access: proxy
        basicAuth: false
        secureJsonData:
           httpHeaderValue1: 'HeaderValue'
           httpHeaderValue2: '1'
        editable: true
        jsonData:
          tlsSkipVerify: true
          httpHeaderName1: 'HeaderName'
          httpHeaderName2: 'X-Scope-OrgID'
        orgId: 1
        type: loki
        url: http://loki-gateway.loki.svc.cluster.local
        version: 1
