apiVersion: v2
name: proto
description: A Helm chart for Kubernetes
type: application
version: 0.0.1

appVersion: "1.0"

dependencies:
  - name: argo-workflows
    version: "0.45.11"
    repository: "https://argoproj.github.io/argo-helm"
