name: hyper-argo-workflows
hostName: &dom workflows.hypermedia.au
ingressMode: ambient
namespace: &ns argo
commonLabels:

argo-workflows:
  namespaceOverride: *ns
  server:
    authModes:
      - server
    ingress:
      enabled: false

  workflow:
    serviceAccount:
      create: true
    rbac:
      create: true
