apiVersion: v2
name: hyper-argocd
description: A chart wrapping kiali  with overridable env affordances
type: application
version: 0.0.1

appVersion: "1.0"

dependencies:
  - name: argo-cd
    version: 7.7.11
    repository: https://argoproj.github.io/argo-helm