
ingressMode: ambient
refreshInterval: 1h
issuerRegion: us-west-2
securityStore:
  kind: ClusterSecretStore
  name: vault-backend
credentials:
  keyPath: ""
  email: ""
dnsZones: []
cert-manager:
  crds:
    enabled: true