apiVersion: v2
name: hyper-jaeger
description: A chart wrapping jaeger tracing interface with overridable env affordances
type: application
version: 1.0.0

appVersion: "1.0"

dependencies:
  - name: jaeger
    version: 3.4.0
    repository: https://jaegertracing.github.io/helm-charts