hostName: ""
ingressMode: ambient
namespace: istio-system
clusterIssuer:
  name: letsencrypt-prod
  kind: ClusterIssuer
jaeger:
  allInOne:
    enabled: true
  collector:
    enabled: false
  agent:
    enabled: false
  query:
    enabled: false
  storage:
    type: memory
  cassandra:
    enabled: false
  provisionDataStore:
    cassandra: false
    elasticsearch: false
    kafka: false
