name: Release Charts

on:
  push:
    branches:
      - main
    paths:
      - charts/**

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.4.0

      - name: add repos
        run: |
          helm repo add argo https://argoproj.github.io/argo-helm
          helm repo add cert-manager  https://charts.jetstack.io
          helm repo add argo-workflows https://argoproj.github.io/argo-helm
          helm repo add crossplane  https://charts.crossplane.io/stable
          helm repo add komoplane https://helm-charts.komodor.io
          helm repo add dynamodb https://keyporttech.github.io/helm-charts/
          helm repo add jaeger https://jaegertracing.github.io/helm-charts
          helm repo add k6-operator https://grafana.github.io/helm-charts
          helm repo add kiali-operator "https://kiali.org/helm-charts"
          helm repo add minio https://operator.min.io
          helm repo add ngrok-operator https://charts.ngrok.com
          helm repo add pihole https://mojo2600.github.io/pihole-kubernetes
          helm repo add postgres https://charts.bitnami.com/bitnami
          helm repo add pgadmin4 https://helm.runix.net
          helm repo add kube-prometheus-stack https://prometheus-community.github.io/helm-charts

      - name: Run chart-releaser
        uses: stecky/yet-another-chart-releaser-action@v1
        env:
          YACR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"